# Generated by Django 4.2.7 on 2025-08-06 17:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('PLN', 'Polish Złoty'), ('EUR', 'Euro'), ('USD', 'US Dollar')], max_length=3)),
                ('customer_id', models.UUIDField()),
                ('product_id', models.UUIDField()),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['customer_id'], name='transaction_custome_72def0_idx'), models.Index(fields=['product_id'], name='transaction_product_5e2c41_idx'), models.Index(fields=['timestamp'], name='transaction_timesta_07633a_idx'), models.Index(fields=['currency'], name='transaction_currenc_cacf11_idx')],
            },
        ),
    ]
